<a href="https://colab.research.google.com/github/dimasbayucmiiw/Kecerdasan-Buatan-2026/blob/main/Data_Preparation_Tugas_Jobsheet_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:
# Import Library yang diperlukan
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeClassifier

In [23]:
df = pd.read_csv('sample_data/iklan_sosmed.csv', delimiter=';')

In [24]:
# Tampilkan 5 Data Pertama
df.head()

         ID Jenis_Kelamin  Umur        Gaji  Transaksi
0  15624510          Pria    19   285000000          0
1  15810944          Pria    35   300000000          0
2  15668575        Wanita    26   645000000          0
3  15603246        Wanita    27   855000000          0
4  15804002          Pria    19  1140000000          0

In [25]:
# Cek apakah ada data yang kosong (NaN)
df.isnull().sum()

ID               0
Jenis_Kelamin    0
Umur             0
Gaji             0
Transaksi        0
dtype: int64

## Data Preparation - One Hot Encoding

In [26]:
# Cek ada berapa data di kolom Jenis_Kelamin
df.Jenis_Kelamin.unique()

array(['Pria', 'Wanita'], dtype=object)

In [27]:
# Lakukan mapping untuk mengubah Pria : 0 dan Wanita : 1
df.Jenis_Kelamin = df.Jenis_Kelamin.map({'Pria':0, 'Wanita':1})

In [28]:
df

           ID  Jenis_Kelamin  Umur        Gaji  Transaksi
0    15624510              0    19   285000000          0
1    15810944              0    35   300000000          0
2    15668575              1    26   645000000          0
3    15603246              1    27   855000000          0
4    15804002              0    19  1140000000          0
..        ...            ...   ...         ...        ...
395  15691863              1    46   615000000          1
396  15706071              0    51   345000000          1
397  15654296              1    50   300000000          1
398  15755018              0    36   495000000          0
399  15594041              1    49   540000000          1

[400 rows x 5 columns]

## Data Preparation - Outlier Removal

In [29]:
# Mencari nilai z-score untuk setiap data point pada kolom Gaji
z_scores_gaji = np.abs((df['Gaji'] - df['Gaji'].mean()) / df['Gaji'].std())

# Mencari nilai z-score untuk setiap data point pada kolom Umur
z_scores_umur = np.abs((df['Umur'] - df['Umur'].mean()) / df['Umur'].std())

In [30]:
# menghilangkan data point yang memiliki z-score lebih besar dari 3 dan menampilkannya
df_clean = df[(z_scores_gaji < 3) & (z_scores_umur < 3)]
df_clean

           ID  Jenis_Kelamin  Umur        Gaji  Transaksi
0    15624510              0    19   285000000          0
1    15810944              0    35   300000000          0
2    15668575              1    26   645000000          0
3    15603246              1    27   855000000          0
4    15804002              0    19  1140000000          0
..        ...            ...   ...         ...        ...
395  15691863              1    46   615000000          1
396  15706071              0    51   345000000          1
397  15654296              1    50   300000000          1
398  15755018              0    36   495000000          0
399  15594041              1    49   540000000          1

[400 rows x 5 columns]

## Data Preparation - Mengambil Dataset

In [31]:
# Melihat korelasi antar kolom
df_clean.corr()

                     ID  Jenis_Kelamin      Umur      Gaji  Transaksi
ID             1.000000       0.025249 -0.000721  0.071097   0.007120
Jenis_Kelamin  0.025249       1.000000  0.073741  0.060435   0.042469
Umur          -0.000721       0.073741  1.000000  0.155238   0.622454
Gaji           0.071097       0.060435  0.155238  1.000000   0.362083
Transaksi      0.007120       0.042469  0.622454  0.362083   1.000000

In [32]:
# Mengambil Umur dan Gaji sebagai Variabel Data dan Transaksi sebagai Variabel Label
X = df.iloc[:,2:-1]
y = df.iloc[:, -1]

In [33]:
# Bagi data menjadi 80% data latih dan 20% ata uji
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

## Data Preparation - Normalization

In [34]:
# normalisasi data gaji dan umur menggunakan MinMaxScaler
scaler = MinMaxScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

## Data Preparation - Cross Validation

In [35]:
# membuat model Decision Tree
dt = DecisionTreeClassifier()

# melakukan 5-fold cross validation
scores = cross_val_score(dt, X_train, y_train, cv=7)

# menampilkan hasil cross validation
print('Hasil cross validation:', scores)

Hasil cross validation: [0.86956522 0.89130435 0.89130435 0.80434783 0.82608696 0.8
 0.88888889]